<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="Cart.aspx.vb" Inherits="Restricted_Cart" %>


<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <form id="form1">
    <div>
        <br />
        <br />
        <asp:Label ID="lblCat" runat="server" Text="Choose a Category" style="font-weight: 700"></asp:Label>
        <br />
        <br />
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True">
            <asp:ListItem Value="0">--Select--</asp:ListItem>
            <asp:ListItem Value="1">Books</asp:ListItem>
            <asp:ListItem Value="2">Movies</asp:ListItem>
        </asp:DropDownList>
        <br />
        <br />
        <asp:Label ID="lblProd" runat="server" Text="Available Products" style="font-weight: 700" Visible="False"></asp:Label>
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateSelectButton="True" DataKeyNames="Pub_ID">
        </asp:GridView>
        <br />
        <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True">
        </asp:GridView>
        <br />
        <asp:Label ID="lblTotal" runat="server" Text="Label" Visible="False" style="font-weight: 700"></asp:Label>
&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lblAmount" runat="server" Text="Label" Visible="False"></asp:Label>
        <br />
        <br />
        <br />
        <asp:Button ID="btnCheckOut" runat="server" Text="Check Out" Visible="False" />
        <br />
        <br />
        <br />
    </div>
       
    </form>
</asp:Content>
